language: python
os:
  - "linux"
python:
  - "3.6"

notifications:
  email:
    recipients:
      - renkeju@gmail.com
    on_success: change
    on_failure: always

install:
  - pip install -r requirements.txt

script:
  - sphinx-build -nW -b html -d _build/doctrees . _build/html
  - touch _build/html/.nojekyll 
  - echo "linux.renkeju.com" > _build/html/CNAME

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  token: $TOKEN  # Set in travis-ci.org dashboard, marked secure
  cleanup: false
  keep_history: true
  on:
    branch: master
  local_dir: _build/html/
